"""Sync every corpus-count surface to the live corpus in one shot.

Single source of truth for the numbers is the KGRAG registry (via
``corpus_status``); the per-book title lists in ``docs/CORPUS.md`` come from the
``corpus/`` directory tree. Running this keeps the following in lock-step so the
README badges, prose, table, and citation can never silently drift again:

  * ``README.md`` — the three shields.io badges (corpus / nodes / edges)
  * ``README.md`` — the "Corpus at a Glance" table (regenerated between markers)
  * ``docs/CORPUS.md`` — the full per-genre book list (via regenerate_corpus_doc)
  * the book, genre, node and edge counts in the prose of README.md,
    docs/index.md, docs/CHAT_UI.md, docs/ingestion-pipeline.md,
    docs/PARTNERS.md and the CITATION.cff abstract (``_PROSE_PATTERNS``)

The partnership blurb used to live in README.md, which is why an earlier version
of this script only ever patched a "N works, X million edges" pattern there. It
moved to docs/PARTNERS.md with different wording (`git log -p` on this file
around 2026-09 shows it) and the pattern was never updated to follow it, so this
sync silently left the new home unpatched -- caught only because the v1.18.1
release audit read every file's actual prose instead of trusting this script's
own "What it updates" claim.

It happened again at v1.26.0: the README intro was reworded to "**253 texts in
21 genres**", which no pattern matched, and docs/index.md, docs/CHAT_UI.md,
docs/ingestion-pipeline.md and CITATION.cff repeated the counts without being
synced at all. All six said 21 genres after Curiosities emptied. Every prose
surface now shares one pattern list, and tests/test_sync_corpus_docs.py fails
when a surface file carries a genre count that no pattern reaches.

The README table is sorted by book count (descending, ties in
``regenerate_corpus_doc.GENRE_ORDER``); ``docs/CORPUS.md`` keeps the canonical
``GENRE_ORDER`` for browsing.

Usage::

    poetry run python scripts/sync_corpus_docs.py            # write changes
    poetry run python scripts/sync_corpus_docs.py --check     # report drift, exit 1 if any

The version badge is intentionally left alone — it tracks the release version and
is owned by the ``/release`` skill, not the corpus.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Make the sibling regenerate script importable and pull in the package.
_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
sys.path.insert(0, str(_SCRIPTS_DIR))

import regenerate_corpus_doc as regen  # noqa: E402

from gutenberg_kg.cli.cmd_status import (  # noqa: E402
    _fmt_badge_nodes,
)
from gutenberg_kg.corpus import corpus_status  # noqa: E402

_REGISTRY_DEFAULT = Path.home() / ".kgrag" / "registry.sqlite"
_README = _REPO_ROOT / "README.md"
# Files whose prose repeats the corpus counts. README.md is patched here too,
# after its table and badges.
_PROSE_SURFACES = [
    _REPO_ROOT / "docs" / "index.md",
    _REPO_ROOT / "docs" / "CHAT_UI.md",
    _REPO_ROOT / "docs" / "ingestion-pipeline.md",
    _REPO_ROOT / "docs" / "PARTNERS.md",
    _REPO_ROOT / "CITATION.cff",
]
_CORPUS_ROOT = _REPO_ROOT / "corpus"

_TABLE_BEGIN = (
    "<!-- BEGIN corpus-table (generated by scripts/sync_corpus_docs.py — do not edit by hand) -->"
)
_TABLE_END = "<!-- END corpus-table -->"


def _render_table(genre_by_corpus: dict[str, dict], totals: dict) -> str:
    """Render the 'Corpus at a Glance' Markdown table in GENRE_ORDER.

    :param genre_by_corpus: Map of ``gutenberg-<slug>`` -> genre stat dict.
    :param totals: The ``totals`` dict from ``corpus_status``.
    :return: The table block including begin/end markers.
    """
    lines = [
        _TABLE_BEGIN,
        "| Genre | Books | Nodes | Edges |",
        "|-------|------:|------:|------:|",
    ]
    rows = []
    for slug in regen.GENRE_ORDER:
        g = genre_by_corpus.get(f"gutenberg-{slug}")
        if not g or g["books"] == 0:
            continue
        rows.append(g)
    # README table reads best largest-first; ties keep GENRE_ORDER (stable
    # sort). docs/CORPUS.md keeps the canonical GENRE_ORDER for browsing.
    rows.sort(key=lambda g: -g["books"])
    for g in rows:
        lines.append(f"| {g['label']} | {g['books']} | {g['nodes']:,} | {g['edges']:,} |")
    lines.append(
        f"| **Total** | **{totals['books']}** | **{totals['nodes']:,}** | **{totals['edges']:,}** |"
    )
    lines.append(_TABLE_END)
    return "\n".join(lines)


def _patch_readme(text: str, status: dict) -> str:
    """Return README text with all corpus-count surfaces updated from *status*."""
    totals = status["totals"]
    genre_by_corpus = {g["corpus"]: g for g in status["genres"]}

    # 1. "Corpus at a Glance" table (between markers).
    table_re = re.compile(re.escape(_TABLE_BEGIN) + r".*?" + re.escape(_TABLE_END), re.DOTALL)
    text = table_re.sub(lambda _m: _render_table(genre_by_corpus, totals), text, count=1)

    return _patch_prose(text, status)


def _counts(status: dict) -> dict[str, int]:
    """Return the numbers the prose patterns fill in.

    :param status: The ``corpus_status`` result.
    :return: ``books``, ``genres``, ``nodes`` and ``edges`` for the whole
        corpus; ``dockg_*`` for the DocKG part (everything but the diaries,
        which DiaryKG indexes); ``prose_*`` for the semantic-chunked part
        (the DocKG part less the verse-chunked sacred texts); and
        ``sacred_books`` and ``diary_books``.
    """
    totals = status["totals"]
    live = [g for g in status["genres"] if g["books"] > 0]
    by_corpus = {g["corpus"]: g["books"] for g in live}
    sacred = by_corpus.get("gutenberg-sacred-texts", 0)
    diary = by_corpus.get("gutenberg-diaries", 0)
    return {
        "books": totals["books"],
        "genres": len(live),
        "nodes": totals["nodes"],
        "edges": totals["edges"],
        "dockg_books": totals["books"] - diary,
        "dockg_genres": len(live) - bool(diary),
        "prose_books": totals["books"] - diary - sacred,
        "prose_genres": len(live) - bool(diary) - bool(sacred),
        "sacred_books": sacred,
        "diary_books": diary,
    }


# (pattern, replacement template). Numbers are the only thing replaced; the
# surrounding words anchor each pattern to one claim, so an unrelated number
# in the same file is never touched.
_PROSE_PATTERNS: list[tuple[str, str]] = [
    # README.md, docs/index.md intro
    (r"\*\*[\d,]+ texts in \d+ genres\*\*", "**{books:,} texts in {genres} genres**"),
    # docs/CORPUS.md-style wording, kept for older prose
    (
        r"[\d,]+ public-domain texts across \d+ genres",
        "{books:,} public-domain texts across {genres} genres",
    ),
    # docs/CHAT_UI.md
    (
        r"DocKG\*\* \([\d,]+ books across \d+ genres\)",
        "DocKG** ({dockg_books:,} books across {dockg_genres} genres)",
    ),
    (
        r"\*\*[\d,]+ books across \d+ genres\*\* in all",
        "**{books:,} books across {genres} genres** in all",
    ),
    # docs/ingestion-pipeline.md
    (
        r"\*\*Current corpus:\*\* [\d,]+ books across \d+ genres",
        "**Current corpus:** {books:,} books across {genres} genres",
    ),
    (r"│   \d+ genres · [\d,]+ books · ", "│   {genres} genres · {books} books · "),
    (
        r"`semantic` \| \d+ genres \([\d,]+ books\)",
        "`semantic` | {prose_genres} genres ({prose_books} books)",
    ),
    (r"`sacred-texts` \(\d+ books\)", "`sacred-texts` ({sacred_books} books)"),
    (r"`diaries` \(\d+ collections\)", "`diaries` ({diary_books} collections)"),
    # docs/ingestion-pipeline.md "Current routing at a glance" table
    (
        r"\| Prose and technical text \| \d+ \| \d+ \|",
        "| Prose and technical text | {prose_genres} | {prose_books} |",
    ),
    (r"\| Sacred texts \| 1 \| \d+ \|", "| Sacred texts | 1 | {sacred_books} |"),
    (r"\| Diaries \| 1 \| \d+ \|", "| Diaries | 1 | {diary_books} |"),
    (
        r"\| \*\*Total\*\* \| \*\*\d+\*\* \| \*\*\d+\*\* \| \|",
        "| **Total** | **{genres}** | **{books}** | |",
    ),
    # CITATION.cff abstract
    (
        r"[\d,]+ works across \d+ genres — [\d,]+ nodes, [\d,]+ edges —",
        "{books:,} works across {genres} genres — {nodes:,} nodes, {edges:,} edges —",
    ),
    # older README intro tail and Docker intro
    (r"— [\d,]+ nodes, [\d,]+ edges — built", "— {nodes:,} nodes, {edges:,} edges — built"),
    (r"query \d+ books", "query {books} books"),
    # docs/PARTNERS.md
    (r"corpus stands at \d+ works", "corpus stands at {books} works"),
]


def _patch_prose(text: str, status: dict) -> str:
    """Return *text* with every corpus count in ``_PROSE_PATTERNS`` updated.

    :param text: File contents.
    :param status: The ``corpus_status`` result.
    :return: The patched contents.
    """
    counts = _counts(status)
    for pattern, template in _PROSE_PATTERNS:
        text = re.sub(pattern, template.format(**counts), text)
    return text


def main() -> int:
    """Sync all corpus-count surfaces; return process exit code."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report drift and exit 1 if anything is stale; do not write.",
    )
    parser.add_argument(
        "--registry",
        default=str(_REGISTRY_DEFAULT),
        help=f"KGRAG registry path (default: {_REGISTRY_DEFAULT}).",
    )
    args = parser.parse_args()

    registry_path = Path(args.registry)
    if not registry_path.exists():
        print(f"[✗] Registry not found: {registry_path}", file=sys.stderr)
        return 2

    status = corpus_status(registry_path, _REPO_ROOT, _CORPUS_ROOT)
    totals = status["totals"]
    genres = sum(1 for g in status["genres"] if g["books"] > 0)

    # --- README ---
    old_readme = _README.read_text(encoding="utf-8")
    new_readme = _patch_readme(old_readme, status)
    # Badges are patched in place by the shared helper on the already-updated text.
    badge_patched = _apply_badges(new_readme, totals)
    new_readme = badge_patched
    readme_changed = new_readme != old_readme

    # --- docs/CORPUS.md ---
    corpus_md = _REPO_ROOT / "docs" / "CORPUS.md"
    old_corpus = corpus_md.read_text(encoding="utf-8") if corpus_md.exists() else ""

    # --- other prose surfaces ---
    prose = {}
    for path in _PROSE_SURFACES:
        old = path.read_text(encoding="utf-8")
        prose[path] = (old, _patch_prose(old, status))
    changed = [path for path, (old, new) in prose.items() if new != old]

    if args.check:
        # Regenerate CORPUS.md into a string without touching disk.
        rows_by_genre, _total = regen._collect_rows()
        new_corpus = regen._render(rows_by_genre, _total, 0.0)
        corpus_changed = _strip_provenance(new_corpus) != _strip_provenance(old_corpus)
        drift = readme_changed or corpus_changed or bool(changed)
        _report(totals, genres, readme_changed, corpus_changed, changed, check=True)
        return 1 if drift else 0

    # --- write ---
    if readme_changed:
        _README.write_text(new_readme, encoding="utf-8")
    for path in changed:
        path.write_text(prose[path][1], encoding="utf-8")
    regen.main()  # writes docs/CORPUS.md with fresh provenance
    new_corpus = corpus_md.read_text(encoding="utf-8")
    corpus_changed = _strip_provenance(new_corpus) != _strip_provenance(old_corpus)
    _report(totals, genres, readme_changed, corpus_changed, changed, check=False)
    return 0


def _apply_badges(text: str, totals: dict) -> str:
    """Apply the three shields.io badge substitutions to *text* (in memory)."""
    import gutenberg_kg.cli.cmd_status as st

    new = text
    new = st._BADGE_PATTERNS["corpus"].sub(f"corpus-{totals['books']}%20books", new)
    new = st._BADGE_PATTERNS["nodes"].sub(f"nodes-{_fmt_badge_nodes(totals['nodes'])}", new)
    new = st._BADGE_PATTERNS["edges"].sub(f"edges-{_fmt_badge_nodes(totals['edges'])}", new)
    return new


def _strip_provenance(text: str) -> str:
    """Drop the timestamp/host provenance lines so content diffs ignore them."""
    keep = []
    for line in text.splitlines():
        if line.startswith("> - Date:") or line.startswith("> - Host:"):
            continue
        if line.startswith("> - Elapsed:") or line.startswith("> - gutenkg:"):
            continue
        if line.startswith("<!-- generated by regenerate_corpus_doc.py"):
            continue
        keep.append(line)
    return "\n".join(keep)


def _report(
    totals: dict,
    genres: int,
    readme_changed: bool,
    corpus_changed: bool,
    changed: list[Path],
    *,
    check: bool,
) -> None:
    """Print a human-readable summary of what changed (or would change)."""
    verb = "would update" if check else "updated"
    same = "would leave unchanged" if check else "already in sync"
    print(
        f"Live corpus: {totals['books']} books · {totals['nodes']:,} nodes · "
        f"{totals['edges']:,} edges · {genres} genres "
        f"(badges: {totals['books']} / {_fmt_badge_nodes(totals['nodes'])} / "
        f"{_fmt_badge_nodes(totals['edges'])})"
    )
    print(f"  {'README.md':<27}{verb if readme_changed else same}")
    print(f"  {'docs/CORPUS.md':<27}{verb if corpus_changed else same}")
    for path in _PROSE_SURFACES:
        name = str(path.relative_to(_REPO_ROOT))
        print(f"  {name:<27}{verb if path in changed else same}")
    if check and (readme_changed or corpus_changed or changed):
        print("\n[✗] Corpus docs are stale — run: poetry run python scripts/sync_corpus_docs.py")
    elif not check:
        print("\n[✓] Corpus docs synced.")


if __name__ == "__main__":
    raise SystemExit(main())
