"""Sync every corpus-count surface to the live corpus in one shot.

Single source of truth for the numbers is the KGRAG registry (via
``corpus_status``); the per-book title lists in ``docs/CORPUS.md`` come from the
``corpus/`` directory tree. Running this keeps the following in lock-step so the
README badges, prose, table, and citation can never silently drift again:

  * ``README.md`` — the three shields.io badges (corpus / nodes / edges)
  * ``README.md`` — the "Corpus at a Glance" table (regenerated between markers)
  * ``README.md`` — the intro prose ("N texts across G genres — X nodes, Y edges")
  * ``README.md`` — the "query N books" line and the "N works, X million edges" blurb
  * ``README.md`` — the BibTeX citation note ("N public-domain texts across G genres")
  * ``docs/CORPUS.md`` — the full per-genre book list (via regenerate_corpus_doc)

The genre *ordering* for the README table is taken from
``regenerate_corpus_doc.GENRE_ORDER`` so both documents share one canonical order.

Usage::

    poetry run python scripts/sync_corpus_docs.py            # write changes
    poetry run python scripts/sync_corpus_docs.py --check     # report drift, exit 1 if any

The version badge is intentionally left alone — it tracks the release version and
is owned by the ``/release`` skill, not the corpus.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Make the sibling regenerate script importable and pull in the package.
_SCRIPTS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPTS_DIR.parent
sys.path.insert(0, str(_SCRIPTS_DIR))

import regenerate_corpus_doc as regen  # noqa: E402

from gutenberg_kg.cli.cmd_status import (  # noqa: E402
    _fmt_badge_nodes,
)
from gutenberg_kg.corpus import corpus_status  # noqa: E402

_REGISTRY_DEFAULT = Path.home() / ".kgrag" / "registry.sqlite"
_README = _REPO_ROOT / "README.md"
_CORPUS_ROOT = _REPO_ROOT / "corpus"

_TABLE_BEGIN = (
    "<!-- BEGIN corpus-table (generated by scripts/sync_corpus_docs.py — do not edit by hand) -->"
)
_TABLE_END = "<!-- END corpus-table -->"


def _render_table(genre_by_corpus: dict[str, dict], totals: dict) -> str:
    """Render the 'Corpus at a Glance' Markdown table in GENRE_ORDER.

    :param genre_by_corpus: Map of ``gutenberg-<slug>`` -> genre stat dict.
    :param totals: The ``totals`` dict from ``corpus_status``.
    :return: The table block including begin/end markers.
    """
    lines = [
        _TABLE_BEGIN,
        "| Genre | Books | Nodes | Edges |",
        "|-------|------:|------:|------:|",
    ]
    for slug in regen.GENRE_ORDER:
        g = genre_by_corpus.get(f"gutenberg-{slug}")
        if not g or g["books"] == 0:
            continue
        lines.append(f"| {g['label']} | {g['books']} | {g['nodes']:,} | {g['edges']:,} |")
    lines.append(
        f"| **Total** | **{totals['books']}** | **{totals['nodes']:,}** | **{totals['edges']:,}** |"
    )
    lines.append(_TABLE_END)
    return "\n".join(lines)


def _patch_readme(text: str, status: dict) -> str:
    """Return README text with all corpus-count surfaces updated from *status*."""
    totals = status["totals"]
    books, nodes, edges = totals["books"], totals["nodes"], totals["edges"]
    genres = sum(1 for g in status["genres"] if g["books"] > 0)
    edges_millions = f"{edges / 1_000_000:.1f}"

    genre_by_corpus = {g["corpus"]: g for g in status["genres"]}

    # 1. "Corpus at a Glance" table (between markers).
    table_re = re.compile(re.escape(_TABLE_BEGIN) + r".*?" + re.escape(_TABLE_END), re.DOTALL)
    text = table_re.sub(lambda _m: _render_table(genre_by_corpus, totals), text, count=1)

    # 2. "N public-domain texts across G genres" — intro prose + citation note.
    text = re.sub(
        r"[\d,]+ public-domain texts across \d+ genres",
        f"{books:,} public-domain texts across {genres} genres",
        text,
    )

    # 3. Intro prose "— X nodes, Y edges — built" tail.
    text = re.sub(
        r"— [\d,]+ nodes, [\d,]+ edges — built",
        f"— {nodes:,} nodes, {edges:,} edges — built",
        text,
    )

    # 4. "query N books" (Docker + local-app intro).
    text = re.sub(r"query \d+ books", f"query {books} books", text)

    # 5. "N works, X.X million edges" (partnership blurb).
    text = re.sub(
        r"\d+ works, [\d.]+ million edges",
        f"{books} works, {edges_millions} million edges",
        text,
    )
    return text


def main() -> int:
    """Sync all corpus-count surfaces; return process exit code."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report drift and exit 1 if anything is stale; do not write.",
    )
    parser.add_argument(
        "--registry",
        default=str(_REGISTRY_DEFAULT),
        help=f"KGRAG registry path (default: {_REGISTRY_DEFAULT}).",
    )
    args = parser.parse_args()

    registry_path = Path(args.registry)
    if not registry_path.exists():
        print(f"[✗] Registry not found: {registry_path}", file=sys.stderr)
        return 2

    status = corpus_status(registry_path, _REPO_ROOT, _CORPUS_ROOT)
    totals = status["totals"]
    genres = sum(1 for g in status["genres"] if g["books"] > 0)

    # --- README ---
    old_readme = _README.read_text(encoding="utf-8")
    new_readme = _patch_readme(old_readme, status)
    # Badges are patched in place by the shared helper on the already-updated text.
    badge_patched = _apply_badges(new_readme, totals)
    new_readme = badge_patched
    readme_changed = new_readme != old_readme

    # --- docs/CORPUS.md ---
    corpus_md = _REPO_ROOT / "docs" / "CORPUS.md"
    old_corpus = corpus_md.read_text(encoding="utf-8") if corpus_md.exists() else ""

    if args.check:
        # Regenerate CORPUS.md into a string without touching disk.
        rows_by_genre, _total = regen._collect_rows()
        new_corpus = regen._render(rows_by_genre, _total, 0.0)
        corpus_changed = _strip_provenance(new_corpus) != _strip_provenance(old_corpus)
        drift = readme_changed or corpus_changed
        _report(totals, genres, readme_changed, corpus_changed, check=True)
        return 1 if drift else 0

    # --- write ---
    if readme_changed:
        _README.write_text(new_readme, encoding="utf-8")
    regen.main()  # writes docs/CORPUS.md with fresh provenance
    new_corpus = corpus_md.read_text(encoding="utf-8")
    corpus_changed = _strip_provenance(new_corpus) != _strip_provenance(old_corpus)
    _report(totals, genres, readme_changed, corpus_changed, check=False)
    return 0


def _apply_badges(text: str, totals: dict) -> str:
    """Apply the three shields.io badge substitutions to *text* (in memory)."""
    import gutenberg_kg.cli.cmd_status as st

    new = text
    new = st._BADGE_PATTERNS["corpus"].sub(f"corpus-{totals['books']}%20books", new)
    new = st._BADGE_PATTERNS["nodes"].sub(f"nodes-{_fmt_badge_nodes(totals['nodes'])}", new)
    new = st._BADGE_PATTERNS["edges"].sub(f"edges-{_fmt_badge_nodes(totals['edges'])}", new)
    return new


def _strip_provenance(text: str) -> str:
    """Drop the timestamp/host provenance lines so content diffs ignore them."""
    keep = []
    for line in text.splitlines():
        if line.startswith("> - Date:") or line.startswith("> - Host:"):
            continue
        if line.startswith("> - Elapsed:") or line.startswith("> - gutenkg:"):
            continue
        if line.startswith("<!-- generated by regenerate_corpus_doc.py"):
            continue
        keep.append(line)
    return "\n".join(keep)


def _report(
    totals: dict, genres: int, readme_changed: bool, corpus_changed: bool, *, check: bool
) -> None:
    """Print a human-readable summary of what changed (or would change)."""
    verb = "would update" if check else "updated"
    same = "would leave unchanged" if check else "already in sync"
    print(
        f"Live corpus: {totals['books']} books · {totals['nodes']:,} nodes · "
        f"{totals['edges']:,} edges · {genres} genres "
        f"(badges: {totals['books']} / {_fmt_badge_nodes(totals['nodes'])} / "
        f"{_fmt_badge_nodes(totals['edges'])})"
    )
    print(f"  README.md      {verb if readme_changed else same}")
    print(f"  docs/CORPUS.md {verb if corpus_changed else same}")
    if check and (readme_changed or corpus_changed):
        print("\n[✗] Corpus docs are stale — run: poetry run python scripts/sync_corpus_docs.py")
    elif not check:
        print("\n[✓] Corpus docs synced.")


if __name__ == "__main__":
    raise SystemExit(main())
